# coding: utf-8

"""
    PURE API 510

    This is the Pure Web Service. Listed below are all available endpoints, along with a short description.<br/>In order to use the Pure Web Service, you must enter an API key. These are generated in the Administrator tab of Pure, and issues with a given set of available endpoints.<br/>To enter your API key and begin your use, press the Authorize button to at the top of the page. You are then presented with two options for entering the API key: the first option is to use the API key in query format, and the second option is to use the API key in a header.<br/> For further documentation, see <a href=\"documentation/Default.htm\">API Documentation</a>.<br/>A new version of the API is released with each major version of Pure, and remains available for one year. This version is no longer available in Pure 5.14<br/>The old web service is deprecated, but still available <a href=\"../../../doc/\">here</a>, and it will no longer be available in Pure 5.13

    OpenAPI spec version: 510
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WSAwardsQuery(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'search_string': 'str',
        'uuids': 'list[str]',
        'size': 'int',
        'offset': 'int',
        'linking_strategy': 'str',
        'locales': 'list[str]',
        'fallback_locales': 'list[str]',
        'renderings': 'list[str]',
        'fields': 'list[str]',
        'orderings': 'list[str]',
        'return_used_content': 'bool',
        'navigation_link': 'bool',
        'id_classification': 'str',
        'type_uris': 'list[str]',
        'period': 'WSCompoundDateRange',
        'financial': 'bool',
        'workflow_steps': 'list[str]',
        'funders': 'WSExternalOrganisationsQuery',
        'external_collaborators': 'WSExternalOrganisationsQuery',
        'internal_collaborators': 'WSOrganisationsQuery',
        'managing_organisational_units': 'WSOrganisationsQuery',
        'for_organisational_units': 'WSOrganisationsQuery',
        'for_persons': 'WSPersonsQuery',
        'for_projects': 'WSUPMProjectsQuery'
    }

    attribute_map = {
        'search_string': 'searchString',
        'uuids': 'uuids',
        'size': 'size',
        'offset': 'offset',
        'linking_strategy': 'linkingStrategy',
        'locales': 'locales',
        'fallback_locales': 'fallbackLocales',
        'renderings': 'renderings',
        'fields': 'fields',
        'orderings': 'orderings',
        'return_used_content': 'returnUsedContent',
        'navigation_link': 'navigationLink',
        'id_classification': 'idClassification',
        'type_uris': 'typeUris',
        'period': 'period',
        'financial': 'financial',
        'workflow_steps': 'workflowSteps',
        'funders': 'funders',
        'external_collaborators': 'externalCollaborators',
        'internal_collaborators': 'internalCollaborators',
        'managing_organisational_units': 'managingOrganisationalUnits',
        'for_organisational_units': 'forOrganisationalUnits',
        'for_persons': 'forPersons',
        'for_projects': 'forProjects'
    }

    def __init__(self, search_string=None, uuids=None, size=None, offset=None, linking_strategy=None, locales=None, fallback_locales=None, renderings=None, fields=None, orderings=None, return_used_content=False, navigation_link=False, id_classification=None, type_uris=None, period=None, financial=False, workflow_steps=None, funders=None, external_collaborators=None, internal_collaborators=None, managing_organisational_units=None, for_organisational_units=None, for_persons=None, for_projects=None):
        """
        WSAwardsQuery - a model defined in Swagger
        """

        self._search_string = None
        self._uuids = None
        self._size = None
        self._offset = None
        self._linking_strategy = None
        self._locales = None
        self._fallback_locales = None
        self._renderings = None
        self._fields = None
        self._orderings = None
        self._return_used_content = None
        self._navigation_link = None
        self._id_classification = None
        self._type_uris = None
        self._period = None
        self._financial = None
        self._workflow_steps = None
        self._funders = None
        self._external_collaborators = None
        self._internal_collaborators = None
        self._managing_organisational_units = None
        self._for_organisational_units = None
        self._for_persons = None
        self._for_projects = None

        if search_string is not None:
          self.search_string = search_string
        if uuids is not None:
          self.uuids = uuids
        if size is not None:
          self.size = size
        if offset is not None:
          self.offset = offset
        if linking_strategy is not None:
          self.linking_strategy = linking_strategy
        if locales is not None:
          self.locales = locales
        if fallback_locales is not None:
          self.fallback_locales = fallback_locales
        if renderings is not None:
          self.renderings = renderings
        if fields is not None:
          self.fields = fields
        if orderings is not None:
          self.orderings = orderings
        if return_used_content is not None:
          self.return_used_content = return_used_content
        if navigation_link is not None:
          self.navigation_link = navigation_link
        if id_classification is not None:
          self.id_classification = id_classification
        if type_uris is not None:
          self.type_uris = type_uris
        if period is not None:
          self.period = period
        if financial is not None:
          self.financial = financial
        if workflow_steps is not None:
          self.workflow_steps = workflow_steps
        if funders is not None:
          self.funders = funders
        if external_collaborators is not None:
          self.external_collaborators = external_collaborators
        if internal_collaborators is not None:
          self.internal_collaborators = internal_collaborators
        if managing_organisational_units is not None:
          self.managing_organisational_units = managing_organisational_units
        if for_organisational_units is not None:
          self.for_organisational_units = for_organisational_units
        if for_persons is not None:
          self.for_persons = for_persons
        if for_projects is not None:
          self.for_projects = for_projects

    @property
    def search_string(self):
        """
        Gets the search_string of this WSAwardsQuery.

        :return: The search_string of this WSAwardsQuery.
        :rtype: str
        """
        return self._search_string

    @search_string.setter
    def search_string(self, search_string):
        """
        Sets the search_string of this WSAwardsQuery.

        :param search_string: The search_string of this WSAwardsQuery.
        :type: str
        """

        self._search_string = search_string

    @property
    def uuids(self):
        """
        Gets the uuids of this WSAwardsQuery.

        :return: The uuids of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._uuids

    @uuids.setter
    def uuids(self, uuids):
        """
        Sets the uuids of this WSAwardsQuery.

        :param uuids: The uuids of this WSAwardsQuery.
        :type: list[str]
        """

        self._uuids = uuids

    @property
    def size(self):
        """
        Gets the size of this WSAwardsQuery.

        :return: The size of this WSAwardsQuery.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """
        Sets the size of this WSAwardsQuery.

        :param size: The size of this WSAwardsQuery.
        :type: int
        """

        self._size = size

    @property
    def offset(self):
        """
        Gets the offset of this WSAwardsQuery.

        :return: The offset of this WSAwardsQuery.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this WSAwardsQuery.

        :param offset: The offset of this WSAwardsQuery.
        :type: int
        """

        self._offset = offset

    @property
    def linking_strategy(self):
        """
        Gets the linking_strategy of this WSAwardsQuery.

        :return: The linking_strategy of this WSAwardsQuery.
        :rtype: str
        """
        return self._linking_strategy

    @linking_strategy.setter
    def linking_strategy(self, linking_strategy):
        """
        Sets the linking_strategy of this WSAwardsQuery.

        :param linking_strategy: The linking_strategy of this WSAwardsQuery.
        :type: str
        """

        self._linking_strategy = linking_strategy

    @property
    def locales(self):
        """
        Gets the locales of this WSAwardsQuery.

        :return: The locales of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._locales

    @locales.setter
    def locales(self, locales):
        """
        Sets the locales of this WSAwardsQuery.

        :param locales: The locales of this WSAwardsQuery.
        :type: list[str]
        """

        self._locales = locales

    @property
    def fallback_locales(self):
        """
        Gets the fallback_locales of this WSAwardsQuery.

        :return: The fallback_locales of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._fallback_locales

    @fallback_locales.setter
    def fallback_locales(self, fallback_locales):
        """
        Sets the fallback_locales of this WSAwardsQuery.

        :param fallback_locales: The fallback_locales of this WSAwardsQuery.
        :type: list[str]
        """

        self._fallback_locales = fallback_locales

    @property
    def renderings(self):
        """
        Gets the renderings of this WSAwardsQuery.

        :return: The renderings of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._renderings

    @renderings.setter
    def renderings(self, renderings):
        """
        Sets the renderings of this WSAwardsQuery.

        :param renderings: The renderings of this WSAwardsQuery.
        :type: list[str]
        """

        self._renderings = renderings

    @property
    def fields(self):
        """
        Gets the fields of this WSAwardsQuery.

        :return: The fields of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """
        Sets the fields of this WSAwardsQuery.

        :param fields: The fields of this WSAwardsQuery.
        :type: list[str]
        """

        self._fields = fields

    @property
    def orderings(self):
        """
        Gets the orderings of this WSAwardsQuery.

        :return: The orderings of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._orderings

    @orderings.setter
    def orderings(self, orderings):
        """
        Sets the orderings of this WSAwardsQuery.

        :param orderings: The orderings of this WSAwardsQuery.
        :type: list[str]
        """

        self._orderings = orderings

    @property
    def return_used_content(self):
        """
        Gets the return_used_content of this WSAwardsQuery.

        :return: The return_used_content of this WSAwardsQuery.
        :rtype: bool
        """
        return self._return_used_content

    @return_used_content.setter
    def return_used_content(self, return_used_content):
        """
        Sets the return_used_content of this WSAwardsQuery.

        :param return_used_content: The return_used_content of this WSAwardsQuery.
        :type: bool
        """

        self._return_used_content = return_used_content

    @property
    def navigation_link(self):
        """
        Gets the navigation_link of this WSAwardsQuery.

        :return: The navigation_link of this WSAwardsQuery.
        :rtype: bool
        """
        return self._navigation_link

    @navigation_link.setter
    def navigation_link(self, navigation_link):
        """
        Sets the navigation_link of this WSAwardsQuery.

        :param navigation_link: The navigation_link of this WSAwardsQuery.
        :type: bool
        """

        self._navigation_link = navigation_link

    @property
    def id_classification(self):
        """
        Gets the id_classification of this WSAwardsQuery.

        :return: The id_classification of this WSAwardsQuery.
        :rtype: str
        """
        return self._id_classification

    @id_classification.setter
    def id_classification(self, id_classification):
        """
        Sets the id_classification of this WSAwardsQuery.

        :param id_classification: The id_classification of this WSAwardsQuery.
        :type: str
        """

        self._id_classification = id_classification

    @property
    def type_uris(self):
        """
        Gets the type_uris of this WSAwardsQuery.

        :return: The type_uris of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._type_uris

    @type_uris.setter
    def type_uris(self, type_uris):
        """
        Sets the type_uris of this WSAwardsQuery.

        :param type_uris: The type_uris of this WSAwardsQuery.
        :type: list[str]
        """

        self._type_uris = type_uris

    @property
    def period(self):
        """
        Gets the period of this WSAwardsQuery.

        :return: The period of this WSAwardsQuery.
        :rtype: WSCompoundDateRange
        """
        return self._period

    @period.setter
    def period(self, period):
        """
        Sets the period of this WSAwardsQuery.

        :param period: The period of this WSAwardsQuery.
        :type: WSCompoundDateRange
        """

        self._period = period

    @property
    def financial(self):
        """
        Gets the financial of this WSAwardsQuery.

        :return: The financial of this WSAwardsQuery.
        :rtype: bool
        """
        return self._financial

    @financial.setter
    def financial(self, financial):
        """
        Sets the financial of this WSAwardsQuery.

        :param financial: The financial of this WSAwardsQuery.
        :type: bool
        """

        self._financial = financial

    @property
    def workflow_steps(self):
        """
        Gets the workflow_steps of this WSAwardsQuery.

        :return: The workflow_steps of this WSAwardsQuery.
        :rtype: list[str]
        """
        return self._workflow_steps

    @workflow_steps.setter
    def workflow_steps(self, workflow_steps):
        """
        Sets the workflow_steps of this WSAwardsQuery.

        :param workflow_steps: The workflow_steps of this WSAwardsQuery.
        :type: list[str]
        """

        self._workflow_steps = workflow_steps

    @property
    def funders(self):
        """
        Gets the funders of this WSAwardsQuery.

        :return: The funders of this WSAwardsQuery.
        :rtype: WSExternalOrganisationsQuery
        """
        return self._funders

    @funders.setter
    def funders(self, funders):
        """
        Sets the funders of this WSAwardsQuery.

        :param funders: The funders of this WSAwardsQuery.
        :type: WSExternalOrganisationsQuery
        """

        self._funders = funders

    @property
    def external_collaborators(self):
        """
        Gets the external_collaborators of this WSAwardsQuery.

        :return: The external_collaborators of this WSAwardsQuery.
        :rtype: WSExternalOrganisationsQuery
        """
        return self._external_collaborators

    @external_collaborators.setter
    def external_collaborators(self, external_collaborators):
        """
        Sets the external_collaborators of this WSAwardsQuery.

        :param external_collaborators: The external_collaborators of this WSAwardsQuery.
        :type: WSExternalOrganisationsQuery
        """

        self._external_collaborators = external_collaborators

    @property
    def internal_collaborators(self):
        """
        Gets the internal_collaborators of this WSAwardsQuery.

        :return: The internal_collaborators of this WSAwardsQuery.
        :rtype: WSOrganisationsQuery
        """
        return self._internal_collaborators

    @internal_collaborators.setter
    def internal_collaborators(self, internal_collaborators):
        """
        Sets the internal_collaborators of this WSAwardsQuery.

        :param internal_collaborators: The internal_collaborators of this WSAwardsQuery.
        :type: WSOrganisationsQuery
        """

        self._internal_collaborators = internal_collaborators

    @property
    def managing_organisational_units(self):
        """
        Gets the managing_organisational_units of this WSAwardsQuery.

        :return: The managing_organisational_units of this WSAwardsQuery.
        :rtype: WSOrganisationsQuery
        """
        return self._managing_organisational_units

    @managing_organisational_units.setter
    def managing_organisational_units(self, managing_organisational_units):
        """
        Sets the managing_organisational_units of this WSAwardsQuery.

        :param managing_organisational_units: The managing_organisational_units of this WSAwardsQuery.
        :type: WSOrganisationsQuery
        """

        self._managing_organisational_units = managing_organisational_units

    @property
    def for_organisational_units(self):
        """
        Gets the for_organisational_units of this WSAwardsQuery.

        :return: The for_organisational_units of this WSAwardsQuery.
        :rtype: WSOrganisationsQuery
        """
        return self._for_organisational_units

    @for_organisational_units.setter
    def for_organisational_units(self, for_organisational_units):
        """
        Sets the for_organisational_units of this WSAwardsQuery.

        :param for_organisational_units: The for_organisational_units of this WSAwardsQuery.
        :type: WSOrganisationsQuery
        """

        self._for_organisational_units = for_organisational_units

    @property
    def for_persons(self):
        """
        Gets the for_persons of this WSAwardsQuery.

        :return: The for_persons of this WSAwardsQuery.
        :rtype: WSPersonsQuery
        """
        return self._for_persons

    @for_persons.setter
    def for_persons(self, for_persons):
        """
        Sets the for_persons of this WSAwardsQuery.

        :param for_persons: The for_persons of this WSAwardsQuery.
        :type: WSPersonsQuery
        """

        self._for_persons = for_persons

    @property
    def for_projects(self):
        """
        Gets the for_projects of this WSAwardsQuery.

        :return: The for_projects of this WSAwardsQuery.
        :rtype: WSUPMProjectsQuery
        """
        return self._for_projects

    @for_projects.setter
    def for_projects(self, for_projects):
        """
        Sets the for_projects of this WSAwardsQuery.

        :param for_projects: The for_projects of this WSAwardsQuery.
        :type: WSUPMProjectsQuery
        """

        self._for_projects = for_projects

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WSAwardsQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
