# coding: utf-8

"""
    PURE API 510

    This is the Pure Web Service. Listed below are all available endpoints, along with a short description.<br/>In order to use the Pure Web Service, you must enter an API key. These are generated in the Administrator tab of Pure, and issues with a given set of available endpoints.<br/>To enter your API key and begin your use, press the Authorize button to at the top of the page. You are then presented with two options for entering the API key: the first option is to use the API key in query format, and the second option is to use the API key in a header.<br/> For further documentation, see <a href=\"documentation/Default.htm\">API Documentation</a>.<br/>A new version of the API is released with each major version of Pure, and remains available for one year. This version is no longer available in Pure 5.14<br/>The old web service is deprecated, but still available <a href=\"../../../doc/\">here</a>, and it will no longer be available in Pure 5.13

    OpenAPI spec version: 510
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WSFundingExpenditureAssociation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'organisation': 'WSOrganisationRef',
        'cost_centers': 'list[WSClassification]',
        'accounts': 'list[WSAccount]'
    }

    attribute_map = {
        'id': 'id',
        'organisation': 'organisation',
        'cost_centers': 'costCenters',
        'accounts': 'accounts'
    }

    def __init__(self, id=None, organisation=None, cost_centers=None, accounts=None):
        """
        WSFundingExpenditureAssociation - a model defined in Swagger
        """

        self._id = None
        self._organisation = None
        self._cost_centers = None
        self._accounts = None

        if id is not None:
          self.id = id
        if organisation is not None:
          self.organisation = organisation
        if cost_centers is not None:
          self.cost_centers = cost_centers
        if accounts is not None:
          self.accounts = accounts

    @property
    def id(self):
        """
        Gets the id of this WSFundingExpenditureAssociation.

        :return: The id of this WSFundingExpenditureAssociation.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this WSFundingExpenditureAssociation.

        :param id: The id of this WSFundingExpenditureAssociation.
        :type: int
        """

        self._id = id

    @property
    def organisation(self):
        """
        Gets the organisation of this WSFundingExpenditureAssociation.

        :return: The organisation of this WSFundingExpenditureAssociation.
        :rtype: WSOrganisationRef
        """
        return self._organisation

    @organisation.setter
    def organisation(self, organisation):
        """
        Sets the organisation of this WSFundingExpenditureAssociation.

        :param organisation: The organisation of this WSFundingExpenditureAssociation.
        :type: WSOrganisationRef
        """

        self._organisation = organisation

    @property
    def cost_centers(self):
        """
        Gets the cost_centers of this WSFundingExpenditureAssociation.

        :return: The cost_centers of this WSFundingExpenditureAssociation.
        :rtype: list[WSClassification]
        """
        return self._cost_centers

    @cost_centers.setter
    def cost_centers(self, cost_centers):
        """
        Sets the cost_centers of this WSFundingExpenditureAssociation.

        :param cost_centers: The cost_centers of this WSFundingExpenditureAssociation.
        :type: list[WSClassification]
        """

        self._cost_centers = cost_centers

    @property
    def accounts(self):
        """
        Gets the accounts of this WSFundingExpenditureAssociation.

        :return: The accounts of this WSFundingExpenditureAssociation.
        :rtype: list[WSAccount]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """
        Sets the accounts of this WSFundingExpenditureAssociation.

        :param accounts: The accounts of this WSFundingExpenditureAssociation.
        :type: list[WSAccount]
        """

        self._accounts = accounts

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WSFundingExpenditureAssociation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
