# coding: utf-8

"""
    PURE API 510

    This is the Pure Web Service. Listed below are all available endpoints, along with a short description.<br/>In order to use the Pure Web Service, you must enter an API key. These are generated in the Administrator tab of Pure, and issues with a given set of available endpoints.<br/>To enter your API key and begin your use, press the Authorize button to at the top of the page. You are then presented with two options for entering the API key: the first option is to use the API key in query format, and the second option is to use the API key in a header.<br/> For further documentation, see <a href=\"documentation/Default.htm\">API Documentation</a>.<br/>A new version of the API is released with each major version of Pure, and remains available for one year. This version is no longer available in Pure 5.14<br/>The old web service is deprecated, but still available <a href=\"../../../doc/\">here</a>, and it will no longer be available in Pure 5.13

    OpenAPI spec version: 510
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WSPressMedia(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'html_renderings': 'list[WSHtmlRendering]',
        'titles': 'list[WSLocalizedString]',
        'types': 'list[WSClassification]',
        'categories': 'list[WSClassification]',
        'descriptions': 'list[WSClassifiedLocalizedValue]',
        'references': 'list[WSReference]',
        'person_associations': 'list[WSClassifiedPersonAssociation]',
        'organisations': 'list[WSOrganisationRef]',
        'external_organisations': 'list[WSExternalOrganisationRef]',
        'managing_organisational_unit': 'WSOrganisationRef',
        'period': 'WSDateRange',
        'keyword_groups': 'list[WSKeywordGroup]',
        'event': 'WSEventRef',
        'related_press_media': 'list[WSPressMediaRef]',
        'related_activities': 'list[WSActivityRef]',
        'related_projects': 'list[WSUPMProjectRef]',
        'related_prizes': 'list[WSPrizeRef]',
        'related_data_sets': 'list[WSDataSetRef]',
        'related_student_thesis': 'list[WSStudentThesisRef]',
        'related_impacts': 'list[WSImpactRef]',
        'related_research_outputs': 'list[WSResearchOutputRef]',
        'visibilities': 'list[WSVisibility]',
        'workflows': 'list[WSWorkflow]',
        'externalable_info': 'WSExternalableInformation',
        'info': 'WSContentInformation'
    }

    attribute_map = {
        'uuid': 'uuid',
        'html_renderings': 'htmlRenderings',
        'titles': 'titles',
        'types': 'types',
        'categories': 'categories',
        'descriptions': 'descriptions',
        'references': 'references',
        'person_associations': 'personAssociations',
        'organisations': 'organisations',
        'external_organisations': 'externalOrganisations',
        'managing_organisational_unit': 'managingOrganisationalUnit',
        'period': 'period',
        'keyword_groups': 'keywordGroups',
        'event': 'event',
        'related_press_media': 'relatedPressMedia',
        'related_activities': 'relatedActivities',
        'related_projects': 'relatedProjects',
        'related_prizes': 'relatedPrizes',
        'related_data_sets': 'relatedDataSets',
        'related_student_thesis': 'relatedStudentThesis',
        'related_impacts': 'relatedImpacts',
        'related_research_outputs': 'relatedResearchOutputs',
        'visibilities': 'visibilities',
        'workflows': 'workflows',
        'externalable_info': 'externalableInfo',
        'info': 'info'
    }

    def __init__(self, uuid=None, html_renderings=None, titles=None, types=None, categories=None, descriptions=None, references=None, person_associations=None, organisations=None, external_organisations=None, managing_organisational_unit=None, period=None, keyword_groups=None, event=None, related_press_media=None, related_activities=None, related_projects=None, related_prizes=None, related_data_sets=None, related_student_thesis=None, related_impacts=None, related_research_outputs=None, visibilities=None, workflows=None, externalable_info=None, info=None):
        """
        WSPressMedia - a model defined in Swagger
        """

        self._uuid = None
        self._html_renderings = None
        self._titles = None
        self._types = None
        self._categories = None
        self._descriptions = None
        self._references = None
        self._person_associations = None
        self._organisations = None
        self._external_organisations = None
        self._managing_organisational_unit = None
        self._period = None
        self._keyword_groups = None
        self._event = None
        self._related_press_media = None
        self._related_activities = None
        self._related_projects = None
        self._related_prizes = None
        self._related_data_sets = None
        self._related_student_thesis = None
        self._related_impacts = None
        self._related_research_outputs = None
        self._visibilities = None
        self._workflows = None
        self._externalable_info = None
        self._info = None

        if uuid is not None:
          self.uuid = uuid
        if html_renderings is not None:
          self.html_renderings = html_renderings
        if titles is not None:
          self.titles = titles
        if types is not None:
          self.types = types
        if categories is not None:
          self.categories = categories
        if descriptions is not None:
          self.descriptions = descriptions
        if references is not None:
          self.references = references
        if person_associations is not None:
          self.person_associations = person_associations
        if organisations is not None:
          self.organisations = organisations
        if external_organisations is not None:
          self.external_organisations = external_organisations
        if managing_organisational_unit is not None:
          self.managing_organisational_unit = managing_organisational_unit
        if period is not None:
          self.period = period
        if keyword_groups is not None:
          self.keyword_groups = keyword_groups
        if event is not None:
          self.event = event
        if related_press_media is not None:
          self.related_press_media = related_press_media
        if related_activities is not None:
          self.related_activities = related_activities
        if related_projects is not None:
          self.related_projects = related_projects
        if related_prizes is not None:
          self.related_prizes = related_prizes
        if related_data_sets is not None:
          self.related_data_sets = related_data_sets
        if related_student_thesis is not None:
          self.related_student_thesis = related_student_thesis
        if related_impacts is not None:
          self.related_impacts = related_impacts
        if related_research_outputs is not None:
          self.related_research_outputs = related_research_outputs
        if visibilities is not None:
          self.visibilities = visibilities
        if workflows is not None:
          self.workflows = workflows
        if externalable_info is not None:
          self.externalable_info = externalable_info
        if info is not None:
          self.info = info

    @property
    def uuid(self):
        """
        Gets the uuid of this WSPressMedia.

        :return: The uuid of this WSPressMedia.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """
        Sets the uuid of this WSPressMedia.

        :param uuid: The uuid of this WSPressMedia.
        :type: str
        """

        self._uuid = uuid

    @property
    def html_renderings(self):
        """
        Gets the html_renderings of this WSPressMedia.

        :return: The html_renderings of this WSPressMedia.
        :rtype: list[WSHtmlRendering]
        """
        return self._html_renderings

    @html_renderings.setter
    def html_renderings(self, html_renderings):
        """
        Sets the html_renderings of this WSPressMedia.

        :param html_renderings: The html_renderings of this WSPressMedia.
        :type: list[WSHtmlRendering]
        """

        self._html_renderings = html_renderings

    @property
    def titles(self):
        """
        Gets the titles of this WSPressMedia.

        :return: The titles of this WSPressMedia.
        :rtype: list[WSLocalizedString]
        """
        return self._titles

    @titles.setter
    def titles(self, titles):
        """
        Sets the titles of this WSPressMedia.

        :param titles: The titles of this WSPressMedia.
        :type: list[WSLocalizedString]
        """

        self._titles = titles

    @property
    def types(self):
        """
        Gets the types of this WSPressMedia.

        :return: The types of this WSPressMedia.
        :rtype: list[WSClassification]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this WSPressMedia.

        :param types: The types of this WSPressMedia.
        :type: list[WSClassification]
        """

        self._types = types

    @property
    def categories(self):
        """
        Gets the categories of this WSPressMedia.

        :return: The categories of this WSPressMedia.
        :rtype: list[WSClassification]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """
        Sets the categories of this WSPressMedia.

        :param categories: The categories of this WSPressMedia.
        :type: list[WSClassification]
        """

        self._categories = categories

    @property
    def descriptions(self):
        """
        Gets the descriptions of this WSPressMedia.

        :return: The descriptions of this WSPressMedia.
        :rtype: list[WSClassifiedLocalizedValue]
        """
        return self._descriptions

    @descriptions.setter
    def descriptions(self, descriptions):
        """
        Sets the descriptions of this WSPressMedia.

        :param descriptions: The descriptions of this WSPressMedia.
        :type: list[WSClassifiedLocalizedValue]
        """

        self._descriptions = descriptions

    @property
    def references(self):
        """
        Gets the references of this WSPressMedia.

        :return: The references of this WSPressMedia.
        :rtype: list[WSReference]
        """
        return self._references

    @references.setter
    def references(self, references):
        """
        Sets the references of this WSPressMedia.

        :param references: The references of this WSPressMedia.
        :type: list[WSReference]
        """

        self._references = references

    @property
    def person_associations(self):
        """
        Gets the person_associations of this WSPressMedia.

        :return: The person_associations of this WSPressMedia.
        :rtype: list[WSClassifiedPersonAssociation]
        """
        return self._person_associations

    @person_associations.setter
    def person_associations(self, person_associations):
        """
        Sets the person_associations of this WSPressMedia.

        :param person_associations: The person_associations of this WSPressMedia.
        :type: list[WSClassifiedPersonAssociation]
        """

        self._person_associations = person_associations

    @property
    def organisations(self):
        """
        Gets the organisations of this WSPressMedia.

        :return: The organisations of this WSPressMedia.
        :rtype: list[WSOrganisationRef]
        """
        return self._organisations

    @organisations.setter
    def organisations(self, organisations):
        """
        Sets the organisations of this WSPressMedia.

        :param organisations: The organisations of this WSPressMedia.
        :type: list[WSOrganisationRef]
        """

        self._organisations = organisations

    @property
    def external_organisations(self):
        """
        Gets the external_organisations of this WSPressMedia.

        :return: The external_organisations of this WSPressMedia.
        :rtype: list[WSExternalOrganisationRef]
        """
        return self._external_organisations

    @external_organisations.setter
    def external_organisations(self, external_organisations):
        """
        Sets the external_organisations of this WSPressMedia.

        :param external_organisations: The external_organisations of this WSPressMedia.
        :type: list[WSExternalOrganisationRef]
        """

        self._external_organisations = external_organisations

    @property
    def managing_organisational_unit(self):
        """
        Gets the managing_organisational_unit of this WSPressMedia.

        :return: The managing_organisational_unit of this WSPressMedia.
        :rtype: WSOrganisationRef
        """
        return self._managing_organisational_unit

    @managing_organisational_unit.setter
    def managing_organisational_unit(self, managing_organisational_unit):
        """
        Sets the managing_organisational_unit of this WSPressMedia.

        :param managing_organisational_unit: The managing_organisational_unit of this WSPressMedia.
        :type: WSOrganisationRef
        """

        self._managing_organisational_unit = managing_organisational_unit

    @property
    def period(self):
        """
        Gets the period of this WSPressMedia.

        :return: The period of this WSPressMedia.
        :rtype: WSDateRange
        """
        return self._period

    @period.setter
    def period(self, period):
        """
        Sets the period of this WSPressMedia.

        :param period: The period of this WSPressMedia.
        :type: WSDateRange
        """

        self._period = period

    @property
    def keyword_groups(self):
        """
        Gets the keyword_groups of this WSPressMedia.

        :return: The keyword_groups of this WSPressMedia.
        :rtype: list[WSKeywordGroup]
        """
        return self._keyword_groups

    @keyword_groups.setter
    def keyword_groups(self, keyword_groups):
        """
        Sets the keyword_groups of this WSPressMedia.

        :param keyword_groups: The keyword_groups of this WSPressMedia.
        :type: list[WSKeywordGroup]
        """

        self._keyword_groups = keyword_groups

    @property
    def event(self):
        """
        Gets the event of this WSPressMedia.

        :return: The event of this WSPressMedia.
        :rtype: WSEventRef
        """
        return self._event

    @event.setter
    def event(self, event):
        """
        Sets the event of this WSPressMedia.

        :param event: The event of this WSPressMedia.
        :type: WSEventRef
        """

        self._event = event

    @property
    def related_press_media(self):
        """
        Gets the related_press_media of this WSPressMedia.

        :return: The related_press_media of this WSPressMedia.
        :rtype: list[WSPressMediaRef]
        """
        return self._related_press_media

    @related_press_media.setter
    def related_press_media(self, related_press_media):
        """
        Sets the related_press_media of this WSPressMedia.

        :param related_press_media: The related_press_media of this WSPressMedia.
        :type: list[WSPressMediaRef]
        """

        self._related_press_media = related_press_media

    @property
    def related_activities(self):
        """
        Gets the related_activities of this WSPressMedia.
        Only available when the Activity module is enabled

        :return: The related_activities of this WSPressMedia.
        :rtype: list[WSActivityRef]
        """
        return self._related_activities

    @related_activities.setter
    def related_activities(self, related_activities):
        """
        Sets the related_activities of this WSPressMedia.
        Only available when the Activity module is enabled

        :param related_activities: The related_activities of this WSPressMedia.
        :type: list[WSActivityRef]
        """

        self._related_activities = related_activities

    @property
    def related_projects(self):
        """
        Gets the related_projects of this WSPressMedia.
        Only available when the Unified Project Model module is enabled

        :return: The related_projects of this WSPressMedia.
        :rtype: list[WSUPMProjectRef]
        """
        return self._related_projects

    @related_projects.setter
    def related_projects(self, related_projects):
        """
        Sets the related_projects of this WSPressMedia.
        Only available when the Unified Project Model module is enabled

        :param related_projects: The related_projects of this WSPressMedia.
        :type: list[WSUPMProjectRef]
        """

        self._related_projects = related_projects

    @property
    def related_prizes(self):
        """
        Gets the related_prizes of this WSPressMedia.
        Only available when the Prize module is enabled

        :return: The related_prizes of this WSPressMedia.
        :rtype: list[WSPrizeRef]
        """
        return self._related_prizes

    @related_prizes.setter
    def related_prizes(self, related_prizes):
        """
        Sets the related_prizes of this WSPressMedia.
        Only available when the Prize module is enabled

        :param related_prizes: The related_prizes of this WSPressMedia.
        :type: list[WSPrizeRef]
        """

        self._related_prizes = related_prizes

    @property
    def related_data_sets(self):
        """
        Gets the related_data_sets of this WSPressMedia.
        Only available when the DataSet module is enabled

        :return: The related_data_sets of this WSPressMedia.
        :rtype: list[WSDataSetRef]
        """
        return self._related_data_sets

    @related_data_sets.setter
    def related_data_sets(self, related_data_sets):
        """
        Sets the related_data_sets of this WSPressMedia.
        Only available when the DataSet module is enabled

        :param related_data_sets: The related_data_sets of this WSPressMedia.
        :type: list[WSDataSetRef]
        """

        self._related_data_sets = related_data_sets

    @property
    def related_student_thesis(self):
        """
        Gets the related_student_thesis of this WSPressMedia.
        Only available when the Student Thesis module is enabled

        :return: The related_student_thesis of this WSPressMedia.
        :rtype: list[WSStudentThesisRef]
        """
        return self._related_student_thesis

    @related_student_thesis.setter
    def related_student_thesis(self, related_student_thesis):
        """
        Sets the related_student_thesis of this WSPressMedia.
        Only available when the Student Thesis module is enabled

        :param related_student_thesis: The related_student_thesis of this WSPressMedia.
        :type: list[WSStudentThesisRef]
        """

        self._related_student_thesis = related_student_thesis

    @property
    def related_impacts(self):
        """
        Gets the related_impacts of this WSPressMedia.
        Only available when the Impact module is enabled

        :return: The related_impacts of this WSPressMedia.
        :rtype: list[WSImpactRef]
        """
        return self._related_impacts

    @related_impacts.setter
    def related_impacts(self, related_impacts):
        """
        Sets the related_impacts of this WSPressMedia.
        Only available when the Impact module is enabled

        :param related_impacts: The related_impacts of this WSPressMedia.
        :type: list[WSImpactRef]
        """

        self._related_impacts = related_impacts

    @property
    def related_research_outputs(self):
        """
        Gets the related_research_outputs of this WSPressMedia.

        :return: The related_research_outputs of this WSPressMedia.
        :rtype: list[WSResearchOutputRef]
        """
        return self._related_research_outputs

    @related_research_outputs.setter
    def related_research_outputs(self, related_research_outputs):
        """
        Sets the related_research_outputs of this WSPressMedia.

        :param related_research_outputs: The related_research_outputs of this WSPressMedia.
        :type: list[WSResearchOutputRef]
        """

        self._related_research_outputs = related_research_outputs

    @property
    def visibilities(self):
        """
        Gets the visibilities of this WSPressMedia.

        :return: The visibilities of this WSPressMedia.
        :rtype: list[WSVisibility]
        """
        return self._visibilities

    @visibilities.setter
    def visibilities(self, visibilities):
        """
        Sets the visibilities of this WSPressMedia.

        :param visibilities: The visibilities of this WSPressMedia.
        :type: list[WSVisibility]
        """

        self._visibilities = visibilities

    @property
    def workflows(self):
        """
        Gets the workflows of this WSPressMedia.

        :return: The workflows of this WSPressMedia.
        :rtype: list[WSWorkflow]
        """
        return self._workflows

    @workflows.setter
    def workflows(self, workflows):
        """
        Sets the workflows of this WSPressMedia.

        :param workflows: The workflows of this WSPressMedia.
        :type: list[WSWorkflow]
        """

        self._workflows = workflows

    @property
    def externalable_info(self):
        """
        Gets the externalable_info of this WSPressMedia.

        :return: The externalable_info of this WSPressMedia.
        :rtype: WSExternalableInformation
        """
        return self._externalable_info

    @externalable_info.setter
    def externalable_info(self, externalable_info):
        """
        Sets the externalable_info of this WSPressMedia.

        :param externalable_info: The externalable_info of this WSPressMedia.
        :type: WSExternalableInformation
        """

        self._externalable_info = externalable_info

    @property
    def info(self):
        """
        Gets the info of this WSPressMedia.

        :return: The info of this WSPressMedia.
        :rtype: WSContentInformation
        """
        return self._info

    @info.setter
    def info(self, info):
        """
        Sets the info of this WSPressMedia.

        :param info: The info of this WSPressMedia.
        :type: WSContentInformation
        """

        self._info = info

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WSPressMedia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
