# coding: utf-8

"""
    PURE API 510

    This is the Pure Web Service. Listed below are all available endpoints, along with a short description.<br/>In order to use the Pure Web Service, you must enter an API key. These are generated in the Administrator tab of Pure, and issues with a given set of available endpoints.<br/>To enter your API key and begin your use, press the Authorize button to at the top of the page. You are then presented with two options for entering the API key: the first option is to use the API key in query format, and the second option is to use the API key in a header.<br/> For further documentation, see <a href=\"documentation/Default.htm\">API Documentation</a>.<br/>A new version of the API is released with each major version of Pure, and remains available for one year. This version is no longer available in Pure 5.14<br/>The old web service is deprecated, but still available <a href=\"../../../doc/\">here</a>, and it will no longer be available in Pure 5.13

    OpenAPI spec version: 510
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WSRankedConcept(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'concept_uuid': 'str',
        'rank': 'float',
        'frequency': 'int',
        'weighted_rank': 'float'
    }

    attribute_map = {
        'concept_uuid': 'conceptUuid',
        'rank': 'rank',
        'frequency': 'frequency',
        'weighted_rank': 'weightedRank'
    }

    def __init__(self, concept_uuid=None, rank=None, frequency=None, weighted_rank=None):
        """
        WSRankedConcept - a model defined in Swagger
        """

        self._concept_uuid = None
        self._rank = None
        self._frequency = None
        self._weighted_rank = None

        if concept_uuid is not None:
          self.concept_uuid = concept_uuid
        if rank is not None:
          self.rank = rank
        if frequency is not None:
          self.frequency = frequency
        if weighted_rank is not None:
          self.weighted_rank = weighted_rank

    @property
    def concept_uuid(self):
        """
        Gets the concept_uuid of this WSRankedConcept.

        :return: The concept_uuid of this WSRankedConcept.
        :rtype: str
        """
        return self._concept_uuid

    @concept_uuid.setter
    def concept_uuid(self, concept_uuid):
        """
        Sets the concept_uuid of this WSRankedConcept.

        :param concept_uuid: The concept_uuid of this WSRankedConcept.
        :type: str
        """

        self._concept_uuid = concept_uuid

    @property
    def rank(self):
        """
        Gets the rank of this WSRankedConcept.

        :return: The rank of this WSRankedConcept.
        :rtype: float
        """
        return self._rank

    @rank.setter
    def rank(self, rank):
        """
        Sets the rank of this WSRankedConcept.

        :param rank: The rank of this WSRankedConcept.
        :type: float
        """

        self._rank = rank

    @property
    def frequency(self):
        """
        Gets the frequency of this WSRankedConcept.

        :return: The frequency of this WSRankedConcept.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """
        Sets the frequency of this WSRankedConcept.

        :param frequency: The frequency of this WSRankedConcept.
        :type: int
        """

        self._frequency = frequency

    @property
    def weighted_rank(self):
        """
        Gets the weighted_rank of this WSRankedConcept.

        :return: The weighted_rank of this WSRankedConcept.
        :rtype: float
        """
        return self._weighted_rank

    @weighted_rank.setter
    def weighted_rank(self, weighted_rank):
        """
        Sets the weighted_rank of this WSRankedConcept.

        :param weighted_rank: The weighted_rank of this WSRankedConcept.
        :type: float
        """

        self._weighted_rank = weighted_rank

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WSRankedConcept):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
